# Generated by Django 4.2 on 2023-12-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
