# Generated by Django 4.2 on 2023-12-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0003_userprofile_is_admin_userprofile_is_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
