# Generated by Django 4.2 on 2023-12-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0001_initial'),
        ('blog', '0006_cartoon_alter_post_image_cartoonpanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartoons', models.ManyToManyField(related_name='saved_by_users', to='blog.cartoon')),
                ('posts', models.ManyToManyField(related_name='saved_by_users', to='blog.post')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users1.userprofile')),
            ],
        ),
    ]
