# Generated by Django 4.2 on 2023-12-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0002_alter_userprofile_user'),
        ('blog', '0007_savedcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcontent',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_content', to='users1.userprofile'),
        ),
    ]
