# Generated by Django 4.2 on 2023-12-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_content1_post_content10_post_content11_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content11',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content12',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image9',
        ),
    ]
